export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const UPDATE_RESULTS_WITH_SELECTION = 'UPDATE_RESULTS_WITH_SELECTION';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const ADD_RESULTS = 'ADD_RESULTS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';

export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';
export const LOAD_GROUPS_FAILED = 'LOAD_GROUPS_FAILED';
export const STORE_GROUP_SELECTED = 'STORE_GROUP_SELECTED';

export const SET_SHOWRESULTS_FLAG = 'SET_SHOWRESULTS_FLAG';
export const RESET_SHOWRESULTS_FLAG = 'RESET_SHOWRESULTS_FLAG';
export const SET_PREV_BUTTON_CLICKED = 'SET_PREV_BUTTON_CLICKED';
export const RESET_PREV_BUTTON_CLICKED = 'RESET_PREV_BUTTON_CLICKED';
export const CURRENT_QUESTION_ID = 'CURRENT_QUESTION_ID';
export const RESET_RESULTS = 'RESET_RESULTS';

export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const LOAD_RESULTS_FAILED = 'LOAD_RESULTS_FAILED';

export const STORE_RESULTS_SUCCESS = 'STORE_RESULTS_SUCCESS';
export const STORE_RESULTS_FAILED = 'STORE_RESULTS_FAILED';

export const SET_TIMESPENT = 'SET_TIMESPENT';
